extern const GeoLayout brige_geo[];
extern Lights1 brige_f3d_material_061_lights;
extern u8 brige_Wood_1_ci8[];
extern u8 brige_Wood_1_ci8_pal_rgba16[];
extern Vtx brige_Cube_mesh_layer_1_vtx_0[24];
extern Gfx brige_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_brige_f3d_material_061[];
extern Gfx mat_revert_brige_f3d_material_061[];
extern Gfx brige_Cube_mesh_layer_1[];
extern Gfx brige_material_revert_render_settings[];
