extern const GeoLayout bowser_3_area_1_geo[];
extern const GeoLayout bowser_3_area_1[];
extern const Collision bowser_3_area_1_collision[];
extern const MacroObject bowser_3_area_1_macro_objs[];
extern Lights1 bowser_3_dl_f3d_material_lights;
extern Lights1 bowser_3_dl_f3d_material_001_lights;
extern u8 bowser_3_dl_icy_wall_ci4[];
extern u8 bowser_3_dl_icy_wall_ci4_pal_rgba16[];
extern u8 bowser_3_dl_krtd_ice_floor_ci4[];
extern u8 bowser_3_dl_krtd_ice_floor_ci4_pal_rgba16[];
extern Vtx bowser_3_dl_Cube_mesh_layer_1_vtx_0[114];
extern Gfx bowser_3_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bowser_3_dl_Cube_mesh_layer_1_vtx_1[40];
extern Gfx bowser_3_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bowser_3_dl_Cube_mesh_layer_1_vtx_2[4];
extern Gfx bowser_3_dl_Cube_mesh_layer_1_tri_2[];
extern Gfx mat_bowser_3_dl_f3d_material[];
extern Gfx mat_revert_bowser_3_dl_f3d_material[];
extern Gfx mat_bowser_3_dl_f3d_material_001[];
extern Gfx mat_revert_bowser_3_dl_f3d_material_001[];
extern Gfx mat_bowser_3_dl_f3d_material_002[];
extern Gfx bowser_3_dl_Cube_mesh_layer_1[];
extern Gfx bowser_3_dl_material_revert_render_settings[];
